# Generated by Django 4.0.5 on 2022-06-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rune_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rune',
            options={'verbose_name': 'Руна', 'verbose_name_plural': 'Руны'},
        ),
        migrations.AddField(
            model_name='rune',
            name='nomer',
            field=models.IntegerField(default=1, verbose_name='Номер столбца'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rune',
            name='picture',
            field=models.ImageField(upload_to='photos/', verbose_name='Графическое изображение'),
        ),
    ]
