# Generated by Django 4.0.5 on 2022-06-15 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_rune_options_rune_nomer_alter_rune_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rune',
            old_name='nomer',
            new_name='count',
        ),
    ]
